# Generated by Django 4.2.6 on 2023-11-29 16:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100, verbose_name='nombre_categoria')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 11, 29, 11, 5, 5))),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 11, 29, 11, 5, 5))),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Archivo')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2023, 11, 29, 11, 5, 5))),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.categoria', verbose_name='Categoría')),
            ],
        ),
    ]
