# Generated by Django 4.2.6 on 2023-11-29 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id_usuario',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 12, 11, 11)),
        ),
        migrations.AlterField(
            model_name='codigo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 12, 11, 11)),
        ),
        migrations.AlterField(
            model_name='document',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 12, 11, 11)),
        ),
    ]
