# Generated by Django 4.2.6 on 2023-11-29 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0003_alter_categoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 15, 57, 57)),
        ),
        migrations.AlterField(
            model_name='codigo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 15, 57, 57)),
        ),
        migrations.AlterField(
            model_name='document',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 15, 57, 57)),
        ),
    ]
