# Generated by Django 4.2.6 on 2023-12-01 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0008_alter_categoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 15, 31, 19)),
        ),
        migrations.AlterField(
            model_name='codigo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 15, 31, 19)),
        ),
        migrations.AlterField(
            model_name='document',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 15, 31, 19)),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 15, 31, 19)),
        ),
    ]
