# Generated by Django 4.2.6 on 2023-12-14 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0009_alter_categoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Codigo',
        ),
        migrations.AddField(
            model_name='document',
            name='contenido_pdf',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido PDF'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 9, 27, 11)),
        ),
        migrations.AlterField(
            model_name='document',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 9, 27, 11)),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 9, 27, 11)),
        ),
    ]
