# Generated by Django 4.2.6 on 2023-12-14 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0010_delete_codigo_document_contenido_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='codigo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 10, 33, 7)),
        ),
        migrations.AlterField(
            model_name='document',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 10, 33, 7)),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 10, 33, 7)),
        ),
    ]
