# Generated by Django 4.2.6 on 2023-12-14 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0011_document_codigo_alter_categoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='contenido_pdf',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 10, 33, 26)),
        ),
        migrations.AlterField(
            model_name='document',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 10, 33, 26)),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 10, 33, 26)),
        ),
    ]
