# Generated by Django 4.2.6 on 2024-02-13 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0021_alter_categoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glosario',
            fields=[
                ('id_termino', models.AutoField(primary_key=True, serialize=False)),
                ('termino', models.CharField(max_length=50, verbose_name='termino')),
                ('definicion', models.TextField(max_length=500, verbose_name='definicion')),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 10, 22, 8)),
        ),
        migrations.AlterField(
            model_name='document',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 10, 22, 8)),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 10, 22, 8)),
        ),
    ]
