# Generated by Django 4.2.6 on 2024-02-13 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0022_glosario_alter_categoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 14, 54, 1)),
        ),
        migrations.AlterField(
            model_name='document',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 14, 54, 1)),
        ),
        migrations.AlterField(
            model_name='glosario',
            name='termino',
            field=models.CharField(max_length=100, verbose_name='termino'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 14, 54, 1)),
        ),
    ]
