# Generated by Django 4.2.6 on 2024-02-29 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0026_alter_categoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 10, 22, 58)),
        ),
        migrations.AlterField(
            model_name='document',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 10, 22, 58)),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=200, upload_to='documents/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 10, 22, 58)),
        ),
    ]
